### ISSUE TITLE
Search Component 내부 요소들 컴포넌트화가 필요합니다.

### ISSUE THREAD

**Issue by onww1** [swsnu/swpp18-team7#22]
Search Component 내에서 다음과 같이 크게 세 가지의 컴포넌트를 만들 수 있을 것 같습니다.

* 검색바 컴포넌트
* Candidate List 컴포넌트
* 검색 결과 컴포넌트

이렇게 세 가지의 컴포넌트를 만든 다음, Candidate List 컴포넌트와 검색 결과 컴포넌트가 서로 다른 스크롤바에 의해서 움직일 수 있도록 만드는 것이 좋을 것 같습니다.

**Comment by dalbamm** [comment]
좋은 의견 감사합니다 반영하겠습니다

**Comment by dalbamm** [comment]
The issue is considered and applied by new _commit_
_commit_ link: https://github.com/swsnu/swpp18-team7/pull/32
